### ISSUE TITLE
slide show stops

### ISSUE THREAD

**Issue by StefanTausK** [diffractor/diffractor#100]
The photo slide show stops after playing one picture. (since v124.0) - In v123.6 it still worked.

**Comment by ZacWalk** [comment]
oh - I was able to repro. Will investigate.

**Comment by ZacWalk** [comment]
The latest build 1125 should have an experimental fix for this. Can be downloaded from the normal link: https://diffractor.com/download

![image](https://user-images.githubusercontent.com/181544/151063453-774fd42c-260f-47bd-a6d5-c8aca95780da.png)

**Comment by StefanTausK** [comment]
it works, thank you
