### ISSUE TITLE
Searching by 'Tags' is not always working. 

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#107]
Hi,
Searching for:
#1980 #1981
fails (but i have many files with these Tags)

Searching one by one:
#1980
And
#1981
Works fine.

Mixed search works ok:
#1980 #"l: eng"

But following fails:
#"l: pol" #"l: eng"

Thanks

**Comment by George-1958** [comment]
Try this   with:#1980 #1981

**Comment by Peceha** [comment]
Nope, still nothing was found..

**Comment by George-1958** [comment]
This with:#1980 #1981  will only show where both tags exist in a file
 This with:#1980 or #1981 will show all files that have either tag

**Comment by Peceha** [comment]
OMG 👍
I totally forgot about OR..
Everything is working now.

Thanks
