### ISSUE TITLE
Location issue.

### ISSUE THREAD

**Issue by aiweller** [diffractor/diffractor#11]
City is not showing correctly after we have set the location. Would be nice to have the option to amend the city and country if they are incorrect. 
Would also be nice to have the option to set the place and state. Currently it is showing City and Country.

**Comment by ZacWalk** [comment]
Implemented in [v123 Beta](https://diffractor.com/blog/Diffractor-v123-Beta). City/State/County can now be edited in the edit view.

**Comment by ZacWalk** [comment]
In v123.3 - the location dialog also allows these values to be entered.

**Comment by ZacWalk** [comment]
@aiweller when you have time could you take a look at the latest version v123.3. I am interested if you think the location dialog works well now. You can download from here: https://diffractor.com/download

Thanks - Zac

**Comment by aiweller** [comment]
Hi @ZacWalk ,

Thank you for the update. It's all I could have asked for.. A few comments while testing;
1. The app crashed a few times
2. the app hung a lot of times
3. When adding a location, sometimes the map is blank
4. On the map, I could see the location that I had input pinned in a red box. but now I am not able to see it anymore. (I've tried restarting, still don't see)

Thank you for the great app and the updates that makes it so much better.

Ashley

**Comment by ZacWalk** [comment]
Ashley thank you for trying that. Sorry about the instability.

1. I see one crash report on my system probably from you. I will try and figure out what caused that. 
2. If you see any pattern with the hanging or find a way to reproduce please let me know. I was not able to figure that out.
3. I was able to reproduce the blank map once. Might be a timing problem. I will try and fix that.
4. Expanding on this last one. Currently, Diffractor does not save places that you enter manually. Is that what you mean? That would be a good feature. When you have time, could you describe how you would expect it to work? 

Hopefully, I am slowly getting there with Diffractor :)
