### ISSUE TITLE
Make Diffractor free

### ISSUE THREAD

**Issue by ZacWalk** [diffractor/diffractor#110]
I have been wanting for a while to make Diffractor free. It is almost free now in that the majority of users don't pay anything. Github has a sponsors feature where users who like diffractor could sponsor it instead.

Diffractor purchases are currently used to fund various costs: development tools, running the website, the code signing certificate, google maps data, etc. I do not make a living from it - I made it because I needed it.

If it becomes free, I am worried users who have paid already may feel unhappy. I am creating this issue to gather feedback.

**Comment by George-1958** [comment]
That is up to you, but i would certainly would still pay for it(maybe a donation system), as i feel this the best program i have have used so far for organizing media, paid or free. This has the potential to develop into something extremely very special.

**Comment by macg12** [comment]
Same as George. Love program. Only disappointed if adverts :-)

**Comment by veereshkumar-dev** [comment]
Hi Zac.. i bough Diffractor last year. 
happy customer :)

Nice to see you are trying to make this available for more ppl. 
but i would recommend you make it so that you would unlock it for a particular machine upon an email request. 
for others who can afford it will happily pay to unlock full features.

good luck, take care man.

**Comment by ZacWalk** [comment]
Thank you @veereshkumar-dev for your support. Maybe in the future, I will be able to do something like that. Create a Pro version or something similar.  The biggest problem is finding a big chunk of free time to work on it :)
