### ISSUE TITLE
Images with duplicate tags causes diffractor to crash

### ISSUE THREAD

**Issue by desbest** [diffractor/diffractor#126]
Images with duplicate tags causes diffractor to crash
It also caused several third party software and windows processes to crash, shortly afterwards.

After you use third party software to give the same image a duplicate tag, upon opening Diffractor, you'll see that the same tag is displayed twice when it should only be displayed once.

I think the crash is caused when I decide to use Diffractor to open such images using an external program from the right click (context) menu.

![pictureflect tagging with a duplicate tag](https://user-images.githubusercontent.com/1139316/187071450-6a8f6fdd-c816-47de-9633-0980a9779b4c.png)

I am using [Pictureflect](https://pictureflect.com/) to give an image duplicate tags, in order to illustrate this bug and maybe how to reproduce it.

Another issue is that if I try to remove the duplicate tag by using the `-` prefix in the tagging window, as the image has a duplicate tag, Diffractor then decides to do nothing with it, so the duplicate tag is neither added again or removed entirely.

I'm using Windows 10 21H2 with 64 bit windows and 64 bit Diffractor at version 125.0.1152

**Comment by ZacWalk** [comment]
Hey desbest. Do you know if this is still an issue? Could you provide a sample image for testing?

**Comment by desbest** [comment]
It works now thrice with the EXIF, XPM and IPTC tags. Thank you for your help!

![diffractor fix with duplicate tags](https://github.com/diffractor/diffractor/assets/1139316/81538e88-cbd0-45a7-b84a-c13eba5f793b)
