### ISSUE TITLE
Diffractor is not displaying correctly multi-byte char

### ISSUE THREAD

**Issue by TonToroJP** [diffractor/diffractor#142]
Diffractor is not displaying file or folder name correctly when that including multi-byte char.

On Windows Explorer:
![11](https://user-images.githubusercontent.com/101859921/200476381-0668877a-6dda-4388-8041-6103cdda31c2.png)

On Diffractor:
![10](https://user-images.githubusercontent.com/101859921/200476344-e865515a-dfb0-4bbe-9636-cbd2c4439e69.png)

Is it possible to fix? Thank you.

**Comment by ZacWalk** [comment]
Hi @TonToroJP. The text rendering in Diffractor uses some old windows API so not sure if I can fix this.
I can try and improve ith though. Could you comment back with some sample text for me to test with?

**Comment by TonToroJP** [comment]
@ZacWalk
Hi Zac, Thank you for reply.

> Could you comment back with some sample text for me to test with?
Sure, I'm using on Japanese Edition of Windows 10. This is sample text: 新しいフォルダー 画像

>The text rendering in Diffractor uses some old windows API
Ok.
And Does font-family display in diffractor's are support multi-byte char?

By the way, excuse me for my English sentence If un-readable, I'm not native speaker so not sure communicate with you correctly. Thank you.

**Comment by laoshucike** [comment]
I encountered similar issues with Chinese characters.
I tried installing older versions and it turned out v123.6 displays correctly and v124.0 doesn't.

**Comment by TonToroJP** [comment]
> 漢字で同様の問題が発生しました。 古いバージョンをインストールしてみましたが、v123.6 は正しく表示され、v124.0 は表示されません。

I'm also confirmed muti-byte char show up correctly on v123.6.

**Comment by ZacWalk** [comment]
I have been trying to get this fixed for a long time, but I believe it is finally solved in Version 126.
Closing this issue but please reopen if not solved.
