### ISSUE TITLE
Language change occurs frequently [bug]

### ISSUE THREAD

**Issue by BMSvsDave** [diffractor/diffractor#149]
Sometimes when starting Diffractor the language is changed automatically, the language I set is always Italian, but sometimes it sets itself to English

**Comment by BMSvsDave** [comment]
sorry for the title changes but I can't insert the BUG label

**Comment by ZacWalk** [comment]
I finally worked out what was causing this. When Diffractor auto-updates it was sometimes overwriting the Language setting. Should be fixed now. Please re-open if still a problem.
