### ISSUE TITLE
Can someone help me?

### ISSUE THREAD

**Issue by BMSvsDave** [diffractor/diffractor#153]
I don't quite understand if this service is still active, I need to talk to the developers of this program, I have published several threads in recent weeks but no one has replied, how is this possible? I turned to Mr. ZacWalk who I think is one of the developers.

Thanks Dave

**Comment by ZacWalk** [comment]
Hi Dave. Sorry, this is just a one man show most of the time. I was taking a break when this came in. I will answer your other issues when I can.
