### ISSUE TITLE
No results when searching folder.

### ISSUE THREAD

**Issue by Aceweo** [diffractor/diffractor#154]
Hi
Have only recently 'found' Diffractor and am impressed with its flexibility and speed.  I do have a question about searching.
I have a folder of scanned photos that I'm currently tagging.  If I type **"#Railways"** or even just **"Railways"** into the search bar all is fine, the whole collection is searched and the correct results but if I type **"H:\Photographs\Scanned Photos #Railways"** (with or without the #) as shown in the Diffractor documentation, I get nothing!
Any ideas what I'm doing wrong
Regards
Tony

**Comment by ZacWalk** [comment]
The most common cause of this is because the folder (H:\Photographs\Scanned Photos) is not indexed.
It is confusing but Diffractor only returns results from indexed folders. Do you think this was what happened here?

**Comment by Aceweo** [comment]
Quite possible thank you for your information
