### ISSUE TITLE
[Feature Request] AV1 image support (.avif)

### ISSUE THREAD

**Issue by dissonator** [diffractor/diffractor#159]
Please add AV1 image support (.avif)

**Comment by ZacWalk** [comment]
In the latest release 126.0, I have tried to resolve AV1 support. Previously Diffractor used ffmpeg's decoding but this is dependant on hardware support for AV1. The new version adds software support. Hopefully AV1 should be now availaible to more people.

I will keep this issue open for a little longer until I am sure this is working for both hardware and software.

**Comment by ZacWalk** [comment]
Reported working in latest version.
