### ISSUE TITLE
Video: Video is not in sync with audio (as example GoPro 12 footage, 8:7 ratio, 3840x3360 hevc)

### ISSUE THREAD

**Issue by RoliKreis** [diffractor/diffractor#160]
If I view a video, as example a GoPro 12 footage, 8:7 ratio, 3840x3360 hevc, it plays to slow. Audio is played in normal speed, but the video is slower. If the audio ends, the progress slider is still not at the end, but the video stops to play. If i set the playback position manually, it starts to play from there, but again the video is slower than the audio playback.
If a video has a length of 63 seconds, it plays up to position "43" (needs 63 seconds for that, because the audio is played in normal speed)
![image](https://github.com/diffractor/diffractor/assets/147135889/e3b8f42d-8ea5-435d-8b23-0be2f1b31b7b)

If I playback the same video footage in Windows Media Player, everything works fine.

Video footage with a smaller resolution (as example GoPro 2.7k footage, 1920x1440), plays normally in Diffractor, video is in sync with audio.

Diffractor Version: 125.0.1161 (Nov 20 2022)
Diffractor General Options: Hardware acceleration is enabled

My hardware:
Processor: 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz, 3504 Mhz, 8 Core(s), 16 Logical Processor(s)
GPU: NVIDIA GeForce RTX 3080

**Comment by ZacWalk** [comment]
That video is high resolution. Might be that Diffractor is not able to decide frames fast enough to keep up with the audio. Could you link a sample video that I can test with?

**Comment by RoliKreis** [comment]
Hello Zac, here are two sample footages
https://1drv.ms/f/s!Aj76YfS3ZDJcgatexy-9MHSLMqxbCw?e=hxeGla

GP12_2-7k_60fps_GX010687.MP4
 - This sample has the effect: 8 seconds long, plays to position "6 seconds" (needs 8 seconds for that)

GP12_FHD_60fps_GX010686.MP4
 - This sample plays normally: To position "8 seconds", in 8 seconds

Greetings, Roli

**Comment by ZacWalk** [comment]
Thanks Roli - those sample videos were very helpful. I can certainly see the problem. Turned out not to be a simple fix. My theory is 2.7k video decoding cant keep up but I am not sure why. I will keep invesatigating.

**Comment by ZacWalk** [comment]
I updated the installer with a possible fix for this issue. If you download from [here](https://diffractor.com/diffractor-setup.exe) you can test it.

I tried a few things, but the simplest fix is to increase the number of threads decoding video. On my test machines that did solve the issue. I am not sure it will solve the problems on all machines. More testing is needed.

**Comment by RoliKreis** [comment]
Thank you for the update! It works perfectly now for Gopro 12, 2.7k, 60fps! At higher resolutions (which I don't use in practice) it can still have the effect that the video plays slower and doesn't play to the end.
My specs: RTX 3080, i9-11900KF
