### ISSUE TITLE
Video Audio only Plays on Diffractor

### ISSUE THREAD

**Issue by area5republik** [diffractor/diffractor#164]
Hi all! I have a series of 5-minute videos that I need to group. The audio is entirely gone when I try to do this in Camtasia or Premiere Pro. I know the audio exists because when using Diffractor to view the single clips, the audio is clear. No other players have the audio for the file, only Diffractor. Could someone explain it to me?

**Comment by ZacWalk** [comment]
Diffractor supports many video and audio codecs. Probably the audio format used in your video does not have codec support in those other players.

**Comment by ZacWalk** [comment]
Closing this as not an issue.
