### ISSUE TITLE
hello admin av1 update or alternative application?

### ISSUE THREAD

**Issue by GlutenFreeVapes** [diffractor/diffractor#165]
Hello admin, this is a great application, one of the best of all time.
However now that AV1 has become more prevalent,
not beinng able to play AV1 video with diffractor has become a sadness in our lives.

Been using OBS and davinic resolve to make av1 clips and vids, 
Diffractor used to be the main application we used to browse videos, tag them, name them, you name it.
There is no application that has come close to it.

If anyone knows a way to fix av1 support or a application that is similar, but supports av1.
Please post here :)

**Comment by ZacWalk** [comment]
I am thinking about how to add support for this. Probably going to use libdav1d. Can you post a link to a sample file I can test with?

**Comment by ZacWalk** [comment]
Release 126 has better AV1 support now. Slowly getting there :)

**Comment by ZacWalk** [comment]
Closing this issue as I have received feedback that AV1 is working in v126. Re-open if more issues.

**Comment by GlutenFreeVapes** [comment]
Thank you so much admin!
This is awesome. Works awesome!

We really appreciate it, this application is a gem!
