### ISSUE TITLE
Japanese translation file

### ISSUE THREAD

**Issue by coolvitto** [diffractor/diffractor#167]
I created a Japanese language file.
Where should I upload the created file?

**Comment by ZacWalk** [comment]
Hi coolvitto. That is awesome, thank you. You can either attach the file here and I will add it to the installer. Otherwise you can submit a pull-request to add it [here](https://github.com/diffractor/diffractor/tree/master/exe/languages).

**Comment by coolvitto** [comment]
Thank you for the advice.

This is Japanese language file for Diffractor v126.0
[ja.zip](https://github.com/diffractor/diffractor/files/15292714/ja.zip)

**Comment by ZacWalk** [comment]
I updated the installer with the Japanese language file. If you download from [here](https://diffractor.com/diffractor-setup.exe) you can test it.

If you have time can you check for the text begin correct? If you see any missing texts let me know and I can help identify what the propblem is.

**Comment by coolvitto** [comment]
I don't think there is any problem with the Japanese language of the installer.

I think many Japanese people would be happy if you included the Japanese language file.

Best regards,
 by coolvitto

**Comment by ZacWalk** [comment]
Sounds good. The Japanese translation file is not in the main release. Thanks for this contribution. If you find any problems or if you create improvements you can create a new issue here. The file used in Diffractor is stored [here](https://github.com/diffractor/diffractor/blob/master/exe/languages/ja.po).
