### ISSUE TITLE
Diffractor 126 does not support Windows 7

### ISSUE THREAD

**Issue by therube** [diffractor/diffractor#169]
[Diffractor] 126.0 does not support Windows 7 (x64), that I can tell.

ZIP download, & extract.
Attempting to run diffractor64.exe or diffractor.exe results in:

The procedure entry point CreateFile2 could not be located in dynamic link library KERNEL32.dll

Version 125 does run in Win7.

<
Dependency Walker:	2.2.6000 (64-bit)
Operating System:	Microsoft Windows NT/2000/XP/2003/Vista based Home Premium (64-bit)
OS Version:	6.01.7601 Service Pack 1
Processor:	Intel64 Family 6 Model 58 Stepping 9, GenuineIntel, ~3093MHz
Number of Processors:	8, Mask: 0x00000000000000FF
Computer Name:	RUBEN
User Name:	RUBEN7
Local Date:	Thursday, May 16, 2024
Local Time:	11:48:32 AM Eastern Daylight Time (GMT-04:00)
OS Language:	0x0409: English (United States)
Memory Load:	40%
Physical Memory Total:	8,456,753,152 (8065 MB)
Physical Memory Used:	3,452,645,376
Physical Memory Free:	5,004,107,776
Page File Memory Total:	26,416,680,960
Page File Memory Used:	5,770,473,472
Page File Memory Free:	20,646,207,488
Virtual Memory Total:	8,796,092,891,136
Virtual Memory Used:	153,067,520
Virtual Memory Free:	8,795,939,823,616
Page Size:	0x00001000 (4,096)
Allocation Granularity:	0x00010000 (65,536)
Min. App. Address:	0x0000000000010000 (65,536)
Max. App. Address:	0x000007FFFFFEFFFF (8,796,092,956,671)
>

(Not that I'm really familiar, but...)
<a href='https://postimg.cc/PPLBLPpm' target='_blank'><img src='https://i.postimg.cc/PPLBLPpm/diffractor126.png' border='0' alt='diffractor126'/></a>

**Comment by ZacWalk** [comment]
oh - removed the call to that API. Can you try downloading the update from:
https://diffractor.com/diffractor-setup.exe

Also you need to install the Windows 7 platform update, if you dont have it already.
https://support.microsoft.com/en-us/topic/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1-d97da9ca-c15c-b21f-ebb0-838f7be8d9f6

It is getting harder to keep it working on Windows 7.

**Comment by therube** [comment]
> Can you try downloading the update from: https://diffractor.com/diffractor-setup.exe

I didn't actually install it, instead simply extracted it's contents, then ran diffractor64.exe,
& ... it works :-).

But, since you took the trouble, I may as well too ;-) ...

Installed, & that too works just fine.


And while we're here, I'll note that it is now (with 126) picking up AV1 mp4 video files which 125 was not.

Thanks for the quick update.


-Steven
(therube)


> Also you need to install the Windows 7 platform update, if you dont have it already.

I had already had that update installed.
     On Thursday, May 16, 2024 at 02:37:07 PM EDT, Zac Walker ***@***.***> wrote:  
 
 


oh - removed the call to that API. Can you try downloading the update from:
https://diffractor.com/diffractor-setup.exe

Also you need to install the Windows 7 platform update, if you dont have it already.
https://support.microsoft.com/en-us/topic/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1-d97da9ca-c15c-b21f-ebb0-838f7be8d9f6

It is getting harder to keep it working on Windows 7.

**Comment by ZacWalk** [comment]
Great news. Thanks for confirming. I will close this issue. Feel free to open a new issue if you see other Windows 7 problems.
