### ISSUE TITLE
Diffractor Closes After Opening

### ISSUE THREAD

**Issue by Bill32606** [diffractor/diffractor#171]
When I open Diffractor it closes after about one second.  I have a notebook computer with Windows 10.  Diffractor has worked on this machine for months and suddenly stopped.

**Comment by ZacWalk** [comment]
Oh no - sorry Bill. Most likely Diffractor upgraded itself to version 126 and there is some problem. Will do my best to fix.

Diffractor creates a log file in its install folder. Could you send that to me. Should be in the following location:
C:\Users\<your user name>\AppData\Local\Diffractor\diffractor.log

**Comment by Bill32606** [comment]
I hope this is it.
    On Friday, May 17, 2024 at 02:10:12 AM EDT, Zac Walker ***@***.***> wrote:  
 
 


Oh no - sorry Bill. Most likely Diffractor upgraded itself to version 126 and there is some problem. Will do my best to fix.

Diffractor creates a log file in its install folder. Could you send that to me. Should be in the following location:
C:\Users<your user name>\AppData\Local\Diffractor\diffractor.log

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |


00016376 00000000 main                             Version: 126.0.1173  |  May 16 2024
00016376 00000094 factories::init                       Intel(R) HD Graphics 620
00016376 00000094 factories::init                       886|5916|7A01028|2
00016376 00000094 factories::init                       DedicatedVideoMemory 128 MB
00016376 00000094 factories::init                       DedicatedSystemMemory 0 KB
00016376 00000094 factories::init                       SharedSystemMemory 3.9 GB
00016376 00000094 resource_font_file_loader::QueryInterfaceE_NOINTERFACE {68648C83-6EDE-46C0-AB46-20083A887FDE}
00016376 00000094 factories::register_fonts        RegisterFontFileLoader 
00016376 00000094 factories::register_fonts        RegisterFontCollectionLoader 
00016376 00000094 app_frame::init                  start
00016376 00000094 control_host_impl::handle_composition_changedcomposition_enabled 1
00016376 00000125 d3d11_draw_context_impl::create  D3D11CreateDevice success 11.1
00016376 00000125 d3d11_draw_context_impl::create       p010 supported
00016376 00000125 d3d11_draw_context_impl::create       nv12 supported
00016376 00000125 create_font_renderer             Created font Consolas
00016376 00000125 create_font_renderer             Created font Calibri
00016376 00000125 create_font_renderer             Created font Calibri
00016376 00000125 create_font_renderer             Created font Calibri
00016376 00000125 resource_font_file_enumerator::MoveNextCreateCustomFontFileReference 0
00016376 00000125 resource_font_file_loader::QueryInterfaceE_NOINTERFACE {68648C83-6EDE-46C0-AB46-20083A887FDE}
00016376 00000125 create_font_renderer             Created font Segoe MDL2 Assets
00016376 00000125 create_font_renderer             Created font Segoe MDL2 Assets
00002772 00000156 start_worker                     start work
00016376 00000156 app_frame::init                  exit
00015532 00000156 start_media_decode_video         start
00013288 00000156 start_media_decode_audio         start
00002820 00000156 start_media_reading              start
00008984 00000156 start_media_preview              start
00008012 00000156 start_database                   start
00013056 00000156 start_worker                     start load
00013048 00000156 start_worker                     start load_raw
00002772 00000156 check_for_updates_and_location   start
00002420 00000156 start_worker                     start render
00014724 00000156 start_worker                     start query
00002800 00000156 start_worker                     start locations
00009488 00000156 start_worker                     start sidebar
00006380 00000156 start_worker                     start auto_complete
00010040 00000156 start_worker                     start web
00008012 00000156 database::open                   Open database: C:\Users\wsw32\AppData\Local\Diffractor\diffractor-cache.db
00005264 00000156 start_worker                     start cloud
00002904 00000156 start_worker                     start index
00008012 00000187 database::open                   Loaded index in 31 ms
00008012 00000187 database::open                   Index open 13.2 MB
00002772 00000266 check_for_updates_and_location   exit
00002008 00000578 start_worker                     start crc
00010368 00000578 start_worker                     start scan_folder
00015436 00000578 start_worker                     start scan_modified_items
00014576 00000578 start_worker                     start scan_displayed_items
00014580 00000578 start_worker                     start predictions
00008428 00000578 start_worker                     start summary
00013452 00000594 start_worker                     start presence
00010004 00000594 start_worker                     start crc
00011148 00000594 start_worker                     start scan_folder
00014584 00000594 start_worker                     start scan_modified_items
00016684 00000594 start_worker                     start scan_displayed_items
00016252 00000594 start_worker                     start predictions
00005620 00000594 start_worker                     start summary
00015288 00000609 start_worker                     start presence
00009312 00002484 recover_callback                 *** recover_callback

**Comment by ZacWalk** [comment]
Hi Bill - I have added more logging to try resolve this. When you have time could you download and re-install from here:
https://diffractor.com/diffractor-setup.exe

You should see the name of any files being processed in the log.

**Comment by Bill32606** [comment]
Hi Zac--thanks for your help.
I re-installed and it failed again.  I see it fails when it tries to index the movies I have saved on my hard drive.  I hope this helps, good luck.
    On Saturday, May 18, 2024 at 03:47:17 AM EDT, Zac Walker ***@***.***> wrote:  
 
 


Hi Bill - I have added more logging to try resolve this. When you have time could you download and re-install from here:
https://diffractor.com/diffractor-setup.exe

You should see the name of any files being processed in the log.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by Bill32606** [comment]
Hi Zac--I moved all my movies off my hard drive and now Diffractor works!  Thanks for your help.  Since I don't need my movies indexed is there any way to turn that off?--Bill
    On Saturday, May 18, 2024 at 03:47:17 AM EDT, Zac Walker ***@***.***> wrote:  
 
 


Hi Bill - I have added more logging to try resolve this. When you have time could you download and re-install from here:
https://diffractor.com/diffractor-setup.exe

You should see the name of any files being processed in the log.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by Bill32606** [comment]
Hi Zac--All my photos have "RGB" and numbers written at the top.--Bill
    On Saturday, May 18, 2024 at 03:47:17 AM EDT, Zac Walker ***@***.***> wrote:  
 
 


Hi Bill - I have added more logging to try resolve this. When you have time could you download and re-install from here:
https://diffractor.com/diffractor-setup.exe

You should see the name of any files being processed in the log.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by Bill32606** [comment]
Thank you very much for all your help.
    On Monday, May 20, 2024 at 03:37:42 PM EDT, Zac Walker ***@***.***> wrote:  
 
 


Sounds like 'show 'debugging application debugging' is turned on in options. If you turn it off things should go back to normal.

image.png (view on web)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by ZacWalk** [comment]
I beleive fixed. Closing.
