### ISSUE TITLE
Folder stats are randomly highlighted

### ISSUE THREAD

**Issue by Sethycakes** [diffractor/diffractor#179]
Hello! Diffractor seems to randomly highlight my folder stats even when I'm not searching for anything. I can't really see any rhyme or reason to these highlights:

![image](https://github.com/diffractor/diffractor/assets/6363204/b8d9f8f8-e08b-45f1-9dd1-b91982e73670)
![image](https://github.com/diffractor/diffractor/assets/6363204/d9c54b05-a217-4f98-b084-3ce3eff3c169)

**Comment by vincenzosalvo** [comment]
Hi think this is an expected behavior due to option "highlight large items in yellow"

![image](https://github.com/user-attachments/assets/081887eb-e590-47d8-8aa2-e6042851def5)

**Comment by ZacWalk** [comment]
This is correct. Larg folders are highlighted in yellow.

**Comment by ZacWalk** [comment]
Closing as a feature :)
