### ISSUE TITLE
Better “customize” screen 

### ISSUE THREAD

**Issue by renochew** [diffractor/diffractor#18]
Is it possible to customize the favourite panel? For example adding new folder or remove existing one. Or removing some group like "countries", etc.

Thank you.

**Comment by ZacWalk** [comment]
Capturing the specific requests I have had for options that should be on this screen:

- [ ] Hide or show the various sections of the sidebar (countries, tags, drives etc)
- [ ] Transparent (from 0 to 100%) for any on screen controls/boxes that obscure the shown photo/media
- [ ] Hide or show various items that show in the media summary panel  (keywords, path, name etc)
- [ ] Hide tooltips that cover the screen/images etc. They are useful only for new users. 
- [ ] Always hide the zoom box unless you hover over it
- [ ] In zoom-pan mode (ctrl-space) hide the zoom box unless you hover over it
