### ISSUE TITLE
Option to toggle on/off playing media at the last known position

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#19]
Hi,
Is it possible to have an option that makes the program forget all playback position for all the videos?

 After a while of browsing throuhg the movies it May be a little bit annoying  when playback starts in the middle or near the end of each video.

Thank you.

**Comment by ZacWalk** [comment]
Sure. I am thinking it could be done a couple of different ways. Either:

- Button somewhere to clear all stored positions.
- Button to toggle off and on playing at the last shown position. If off videos would always play from the start. 

@Peceha any thoughts which approach is more useful?

**Comment by Peceha** [comment]
I would vote for a toggle button. 
That way the position is always there and program just respects/ignores it when the playback starts.

**Comment by ZacWalk** [comment]
Cool - I think toggle does seem best. I will add in an upcoming version.

**Comment by ZacWalk** [comment]
Build 1126 released today has an option on the options screen for this. Let's see how useable that is. I could also add it to the playback menu but there are already a lot of things in there.

![image](https://user-images.githubusercontent.com/181544/151261128-7399d69f-1eb2-4961-ae26-2fedfa6c1286.png)

**Comment by Peceha** [comment]
So far so good. 
Have been playing around for a while and the new option seems to work fine.

Thanks 👍
