### ISSUE TITLE
Incorrect import

### ISSUE THREAD

**Issue by bjones1** [diffractor/diffractor#24]
When I import a large number of photos, the dates they're imported to are incorrect unless I first manually scroll through all the photos, waiting for Diffractor to load their thumbnails and metadata. I'm guessing that the import code doesn't check to verify that the metadata associated with each image to import is loaded before it does the import.

**Comment by ZacWalk** [comment]
Thanks for reporting this @bjones1. I will fix this in the next release. You guessed it correctly.

**Comment by bjones1** [comment]
Thanks!

**Comment by ZacWalk** [comment]
Fixed in v122.15
