### ISSUE TITLE
"Genre" metadata problems

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#34]
Hi,
I spotted this a while ago but forgot to inform.
- "Genre" metadata cannot be saved - the field always stays empty.
- "Genre" dropdown menu is populated many, many times with the same entries. Moreover it looks like every time you open edit window there are more and more entries under that dropdown menu ("Genre").

Thanks

**Comment by ZacWalk** [comment]
Thanks @Peceha - will fix in 122.16.
