### ISSUE TITLE
"Sort By -> default" is ignoring some keywords

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#4]
Hi
Since "Sort By -> default" is grouping by "show" field (it seems so) I just noticed it ignores many words (written into this field) and puts most of videos under "videos" group.

Thanks

**Comment by Peceha** [comment]
Ahhh,
I think I know what's going on.
If there is only one video with eg. "show=blabla" it won't be placed in separate group.
But as soon as I add "show=blabla" to another video then both of them will create a group.
So maybe it is not an issue after all ...

Thanks

**Comment by ZacWalk** [comment]
That is correct. Default sorting only splits out groups of albums in a show or album. However it it makes me wonder if 'sort by show' would be a useful enhancement.

**Comment by Peceha** [comment]
Hi, 
thanks for the answer, well .. if it is not a huge amount of work then why not :)
But just in case I tried to show on pictures what I mean in the first place.

And thanks for that program !
It is something I've been looking for for years !!

![1](https://user-images.githubusercontent.com/67386110/87451428-21f18f00-c600-11ea-8ee0-869353c3748b.jpg)
![2](https://user-images.githubusercontent.com/67386110/87451450-28800680-c600-11ea-8f50-6a0bc6072372.jpg)
![3](https://user-images.githubusercontent.com/67386110/87451462-2c138d80-c600-11ea-970b-b6b94232ab9e.jpg)

**Comment by ZacWalk** [comment]
Interesting to think about this. To me, the default search is better to only group items by show and album when there are multiple items in the group. My suggestion would be to add sort by 'show/album' that is similar but allows show groups to have 1 or more items. Not much work but I am not planning to release 122.9 until September so might take a while. (I am travelling at the moment so a limited with what work I can do)

@Peceha thanks for the clarifying diagrams and positive feedback (y)

**Comment by Peceha** [comment]
That solution sounds perfect.
Thank You.

**Comment by ZacWalk** [comment]
Added in [122.9](https://diffractor.com/blog/Diffractor-122-9)

**Comment by Peceha** [comment]
It's been already one month since the update but finally I got my hands on it ;) - working at sea, not much time for fun, Hehe.
Thanks for implementing the sugestions and for keeping the project alive!

**Comment by ZacWalk** [comment]
I think this is done. Closing.
