### ISSUE TITLE
missing "scope" in search link

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#40]
Hi,
it is about latest v.123 beta
Please adjust the title - I'm afraid I just couldn't figure out the correct one in English :)

Back to the subject: 
in the previous version whenever you clicked on a field (under file preview - left side window), that field was shown in the search box AND WAS PRECEDED with a "marker" (eg: # for tag, "artist" for artist and so on , depends which field you clicked)
In latest v.123 Beta selected word just shows up in the search box without anything in front thus the search result gives all possible findings in all fields + file names forcing you to precede the word manually with the correct "marker"

Thanks.

**Comment by ZacWalk** [comment]
oh - I know what you mean.  Those are called scopes. I will fix the release of v123.

**Comment by ZacWalk** [comment]
Fixed in today's build of version 123. Updated on website - https://diffractor.com/download
