### ISSUE TITLE
Windows 10 - window snapping not working with keyboard

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#48]
Hi,
it was working with previous versions but it is not working with v.123
Pressing "windows key" + "left/right arrow" does nothing, and with "down arrow" works only when the Diffractor window is already maximized.

Thanks.

**Comment by ZacWalk** [comment]
Fixed in today's build of version 123. Updated on website - https://diffractor.com/download
Turns out this breaks if the main Window does not have the WS_THICKFRAME style.
