### ISSUE TITLE
metadata info doesn't get updated on the screen (in some cases)

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#49]
Hello :) it's me again...
I have to report one new bug (for today's version) - it is going to be a little difficult to explain.

When I'm changing the metadata of a file that I navigated to via the "indexed folders" part of the Side Bar - all is fine, the program shows updated information just after I press SAVE in Edit Window.

But when I try to change metadata of the file that I reached from any other Side Bar entry (favorites, tags) then after saving my new changes the program still shows old metadata. Entering again Edit Window also shows old metadata inside  - it looks like nothing was saved at all, but that is not true.
To make Diffractor to show updated metadata (in main program window and in Edit Window) I need to choose whatever entry in Side Bar and then come back the the old one.

Wow, I do hope You will understand :)

**Comment by ZacWalk** [comment]
oh - nice detective work on that. I know what you mean. I will investigate.

**Comment by ZacWalk** [comment]
@Peceha I have a fix for this in today's build at: https://diffractor.com/download
Could you give it a try and see if it works for you?

**Comment by Peceha** [comment]
I tried the file from link above (today's built, apr-27) and unfortunately it still doesn't update the info.

**Comment by ZacWalk** [comment]
Thanks for testing it. If the build date says 27 then it should have a fix. I was able to repro an issue and find a race condition that I thought was causing it. Maybe I need more details:

- What type of file? Jpeg or raw etc?
- What metadata field did you edit?

**Comment by Peceha** [comment]
OK, I didn't tell you everything.. it was a video file not a picture
I just tested with the picture and it works fine, but with the videos (details you can see on one of the pictures) still no updates.

starting position:
![metadata-3](https://user-images.githubusercontent.com/67386110/116229312-a14aec00-a756-11eb-8d1f-bc58cdc8389a.jpg)

here I added "test" everywhere I could
![metadata](https://user-images.githubusercontent.com/67386110/116229385-b6277f80-a756-11eb-91f5-28d825dffb3d.jpg)

this one is after clicking SAVE - the "test" is not showing up
![metadata-2](https://user-images.githubusercontent.com/67386110/116229448-d1928a80-a756-11eb-8872-938b588f5f17.jpg)
![metadata-3](https://user-images.githubusercontent.com/67386110/116229533-e838e180-a756-11eb-96d8-d98de9f4e18c.jpg)

**Comment by ZacWalk** [comment]
Hi @Peceha - could you try one more version from here - https://diffractor.com/diffractor-setup.exe
Should have 28th as the build date.

**Comment by Peceha** [comment]
Hi,
build date is 28th so I'm checking today's version
but I'm afraid I still have bad news...
It is working fine but only when the file was picked via "indexed folders".
When the file was chosen via "Favorite Searches" and "Favorite Tags" still no update.

Just one more observation - pressing F5 updates the info display under video (and in Edit Window the updated info shows up as well)

Thanks for working on that , I can only image how frustrating it can be...

**Comment by ZacWalk** [comment]
ok - I was able to repro with longer files (over 30 mins). Might be some race condition based on the file size. I will get keep going!

**Comment by Peceha** [comment]
I wanted to download v.122.16 and .15 to be sure that the problem is not coming from windows itself.

but don't know how to install it - install window shows the correct version (122.16, 122.15) but when the program starts , the About dialog tells me its v.123.0

**Comment by ZacWalk** [comment]
The problem does not seem to exist in the v122 versions. This is likely because v123 has some new internal caching. The 122 installers did not support sowngrades. The v123 installer can downgrade.

**Comment by ZacWalk** [comment]
Quick update - to fix this I changed some low-level threading stuff. I need to test it well before I release a build - that is taking time. Hopefully, I will have a fix available on Monday for you to try.

**Comment by Peceha** [comment]
Can't wait to put my hands on it :)

**Comment by ZacWalk** [comment]
Hi @Peceha - that took longer than expected. I have an updated version - https://diffractor.com/diffractor-setup.exe
Could you try it when you have time?

**Comment by Peceha** [comment]
PERFECT :)
The updated info is showing right away (version 123.1 from may 5th)
I tested with few files from different locations and all of them work perfect
Thank you!!

PS.
Could be that new update introduces one new .. glich .. not a big deal anyway.
When I opened today's version one of my indexed folders was gone from the folder list thus all the files inside that folder were not shown in Diffractor.
Luckily , I only needed to open preferences and pick that folder again - then all files came back together with all metadata I set. 

Anyway, really good job with the program!

**Comment by ZacWalk** [comment]
Cool - I will close this out. Thanks for confirming.

I have been simplifying various dialogs including the index options. Looks like that has broken the folder list - because I removed the first extra folder. I will fix the for the next build.
