### ISSUE TITLE
Update 123.1 Wrong Version number.

### ISSUE THREAD

**Issue by sflorg** [diffractor/diffractor#52]
Updates yet still has Version # 123.0 and continues to indicate update needed. Though update date is correct.

**Comment by ZacWalk** [comment]
Thanks for reporting that. Looks like a build script issue. It is the correct version but built with the wrong version number. I will fix it in the next few hours. :+1:

**Comment by sflorg** [comment]
Figured as much, but the one that needs to be thanked is you for your quality program. Really like the changes, yet way underpriced. . . Not complaining though😁
Heidi-Ann

**Comment by ZacWalk** [comment]
Glad you like it - slowly getting better - step by step. 
Hopefully, I can compensate for the low price with more customers. ... so recommend it to your friends :)

**Comment by ZacWalk** [comment]
Fixed in current latest build.
