### ISSUE TITLE
Thumbnail View changes to Details View

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#53]
Hi,
just testing the latest version (5th may) and there seems to be strange behavior when browsing MOVIES:

It happens only when indexed folder is chosen from Side Bar (any other location works fine)
- select indexed folder
- make sure the view is set to Thumbnails
- scroll quickly down - you will notice that at some point the thumbs will be replaced with the Detail View .... or instead of scrolling keep changing the movies (keep clicking on thumbnails) - after few changes thumbnails will be replaced with Detail View.

The last action (clicking on thumbnails) sometimes can give different result:
every few changes of videos, the preview remains from last file (only paused picture) but music starts playing from the new one, clicking next file fixes this and then again after few changes it happens again

Thank you - I know you are going to fix it :), hehe

**Comment by ZacWalk** [comment]
That is an interesting one. I did see something similar a few days ago but could not reproduce it.
How are you sorting and grouping the items - and how many videos are in the list?
I am running out of time today - will work on a fix tomorrow - at least I won't be bored :)

**Comment by ZacWalk** [comment]
There is also something weird with AVI files. Some files get stuck before playing or never show video - only audio. Are you seeing this with AVI files?

**Comment by Peceha** [comment]
It happens only when indexed folder is selected AND the program is in root of the indexed folder (what I mean, you do not go to any of subfolders  if there are any - if you go to subfolders all is working fine - so only the very first level is problematic)

it happens only in following Grouping (at least for me):
album/show
camera
location
rating

these groupings will change the view from Thumbs to Details automatically when you select them from the drop down menu (and being in the root folder only -> this could be a lead), when selecting some other like DATE CREATED will keep the thumb view

Sorting has no impact.

-----
It happens more frequently if there are more files in the folder.
I stared with 30 files and it happened few times but not so often and the more I clicked the program was more and more stable (the view was not changing so frequently)
Then I increased the number of files to ~60 and again it stared but the more I clicked/scrolled it was happening less and less.
When I put >300 files it was much easier to get the view changed.

**Comment by Peceha** [comment]
Unfortunately I have no AVI - not even one, but I've never seen this so far with the containeres/codecs I use.
If I experience this I will let you know right away.

**Comment by ZacWalk** [comment]
Thanks, @Peceha - I am going to have a fix probably tomorrow for displaying video problems. 
Diffractor is scanning videos for metadata during loading them and this can take time if the file is long. 
The layout code was running before the video was fully loaded.
The issue above is probably similar and I think caused by frame size changes in the video stream. I hope to fix this also.

**Comment by ZacWalk** [comment]
ok - still not a new version yet. I keep finding weird video playback problems. Getting close - I hope :)

**Comment by Peceha** [comment]
I'm sure you'll fix it but just in case I keep my fingers crossed, hehe

**Comment by ZacWalk** [comment]
Hey @Peceha - I always get there in the end - but not always quickly :)
I have an experimental v123.2 here -> https://diffractor.com/diffractor-setup-test.exe
It should fix the two main issues reported here and a few extra things.
When you have time could you try it.
It is still not fully tested - please let me know if you see anything weird.

**Comment by Peceha** [comment]
Thank You !! :)
V.123.2 (14th may)
- the view doesn't change by itself anymore from Thumb to Details
- both the video and audio streams play every time I change the file
- the corrupted video from few posts above is no longer corrupted - plays nicely

I'll keep testing and if something comes up I'll let you know.
Thanks for great support !!

**Comment by ZacWalk** [comment]
Great news!. -V123 was such a big change that there have been a lot of small issues.
Hopefully, it is stabilizing now. 
Thanks for testing - let me know if you see any other bugs.

**Comment by ZacWalk** [comment]
Complete
