### ISSUE TITLE
"artist" scope - comes together with "album" scope

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#54]
Dobré ráno :)

just a small thing:
please look at the pictures, you will se that hoovering over ARTIST icon shows a combined scope (ALBUM + ARTIST) thus following search action fails.
![Clipboard Image (1)](https://user-images.githubusercontent.com/67386110/119142669-0f798a80-ba47-11eb-9eca-c9d3092a7d0a.jpg)
![Clipboard Image (2)](https://user-images.githubusercontent.com/67386110/119142681-12747b00-ba47-11eb-8f37-1006ab634501.jpg)

Thanks

**Comment by ZacWalk** [comment]
Interesting: album.artist is a separate metadata field to the artist. As listed here: https://github.com/diffractor/diffractor/wiki/Metadata

That artist data could come from the album.artist field or the artist field. Looks like the search always assumes album.artist. I will fix in the next minor release. 

Thanks for reporting this.

**Comment by Peceha** [comment]
I thing you are right.
When I click on the artist name (first picture) then search box shows: album.artist: ...and nothing is found
When I manually remove album. (leaving just artist: and pressing Enter) then I get the correct search results.

**Comment by ZacWalk** [comment]
Should be fixed in the latest update on the website now.

**Comment by ZacWalk** [comment]
Done in v123.4

**Comment by Peceha** [comment]
Wow, you managed to fixed a lot in 123.4 - there will be nothing left to fix in future releases, hehe.
Thanks !

**Comment by ZacWalk** [comment]
hopefully - I fix more things than I break :)
