### ISSUE TITLE
folders thumbnails overlap (sometimes) horizontal line divider and first group name

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#56]
Hi,
just like on the picture - I wish I could tell you more but I was not able to find out any pattern for this - some thumbs are displayed correctly, some are not.

![Clipboard Image (1)](https://user-images.githubusercontent.com/67386110/119269671-1e07a380-bbf9-11eb-880f-f407cdae6e39.jpg)

![Clipboard Image (2)](https://user-images.githubusercontent.com/67386110/119269840-04b32700-bbfa-11eb-89bf-abea1445b490.jpg)

Thanks :)

**Comment by ZacWalk** [comment]
I have not been able to repro this but I do see folder thumbnails not draw with the correct aspect ratio. Is it only folders where you see the issue?

**Comment by Peceha** [comment]
Yes, it happens only with folders.
It is even possible to fix it if I play with the pictures inside (add or delete some).

Could it be because of some foulty pic inside? But if yes then single thumb for that picture also should be incorect... 

Ok, after weekend I'll do more testing hopefuly I will find some clue.

**Comment by ZacWalk** [comment]
I plan to fix the aspect ratio problem tomorrow. That will give me a chance to review the drawing code for folder thumbnails. Hopefully, I discover something wrong there :)

**Comment by ZacWalk** [comment]
The Thumbnail layout code has been re-written in v123.4. @Peceha are you still able to repro?

**Comment by Peceha** [comment]
Hi Zac,
I have good news and a little bit worse (but I may have a lead...)

All the thumbs have the correct aspect ratio now - strange proportions are gone forever.

Unfortunately there is still one "wrong calculation" going on somewhere.
It only happens when:
-the new row of folder thumbs gets created
-always applies to the very last row (when there is only one folder thumb in it)
-gets fixed when you add another folder later on

1. Start - all fine here
![image](https://user-images.githubusercontent.com/67386110/122036558-fd83d100-cdd3-11eb-9f07-028d19209fa7.png)

2. I add one folder here so the program creates a new row in FOLDER part - things get worse (horizontal divider overlaps new thumb and the text is also overlapping the text below it)
![image](https://user-images.githubusercontent.com/67386110/122036789-3f147c00-cdd4-11eb-9ae4-0e1f11a2c7d2.png)

3. Adding another folder fixes everything
![image](https://user-images.githubusercontent.com/67386110/122036911-5d7a7780-cdd4-11eb-8b30-738f53570a8a.png)

The whole scenario will repeat when new row of folders is going to be created.

Anyway, the things are getting better and better with every update you make!
Thank you!

**Comment by ZacWalk** [comment]
ok - I think I fixed this one also. I updated the release on the website. SHould be fixed in build 1020.

**Comment by Peceha** [comment]
Yes, build 1020 fixes that issue!
Thanks.

**Comment by ZacWalk** [comment]
Awesome!! :beer:
