### ISSUE TITLE
Not all keyboard shortcuts are working in Edit Window

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#59]
Hi Zac,
this is really nothing big - up to now there are 2 shortcuts I've been using when in (E)dit Window:
ESC - to close it without saving
CTRL SHIFT ENTER - to save and close
both are working fine.

But.. there are 2 other shortcuts:
CTRL SHIFT LEFT/RIGHT - and pressing them has no effect at all

Thanks
Piotrek

**Comment by ZacWalk** [comment]
Looks like a problem when the focus is in an edit box. 
The edit box uses that shortcut for select to the end of the line. 
Probably best if I change the shortcut to ALT LEFT/RIGHT

**Comment by Peceha** [comment]
ALT LEFT/RIGHT sounds good - but, in that case, what are you going to do with CTRL SHIFT ENTER ? Leave it? Or change to ALT ENTER?
In my opinion ALT ENTER would be better - just the same "control" keys for all , unless ALT ENTER is also used by window's edit box...

**Comment by ZacWalk** [comment]
This is now done in the latest update on the website. 
@Peceha thanks for the other bug reports. I am working thru them .. hard to keep up :)

**Comment by Peceha** [comment]
Just checked the latest one (11.jun) and the keyboard shortcuts do work in Edit Window (Alt+...)
Thanks :)

... and adding more "labels" was really a great idea.

**Comment by ZacWalk** [comment]
Done in v123.4
