### ISSUE TITLE
changing system speakers volume (fn+...) affects Diffractor internal volume level

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#60]
Hi,
that one confused me at first but now it is clear:
- start Diffractor
- start a movie
- use your laptop's fn+... combination to change the system's speakers volume - you will see that every press on the keyboard changes Diffractor's volume icon (so just with few presses you can mute the sound) 

Thanks

**Comment by ZacWalk** [comment]
Diffractor is handling:

VK_VOLUME_DOWN
VK_VOLUME_MUTE
VK_VOLUME_UP

These key presses also affect global audio settings. I guess Diffractor should ignore and leave to the system. 

One extra case is if you are using more than one audio device. Like headphones and speakers. I will do some experiments to see what happens.

**Comment by Peceha** [comment]
Somehow I did not think about that - but now you mentioned it I do recall some video players have an option to disable/enable controlling the global settings via these special keys - so actually it is not a bug but just a design choice (whatever it means :) )

![image](https://user-images.githubusercontent.com/67386110/121676648-272bb800-cab5-11eb-810f-cf70d971089b.png)

**Comment by ZacWalk** [comment]
After some testing with multiple devices etc; seems best for Diffractor not to handle these key presses. Diffractor sends Audio through the main mixer. The mixer should handle those key presses. 
Thanks again @Peceha  !

**Comment by ZacWalk** [comment]
Implemented in v123.4
