### ISSUE TITLE
Wrong thumbnail gets highlighted when scrolling with mouse

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#62]
Hi,
after yesterday's extensive testing of new version :) I accidentally noticed a small visual issue when scrolling in "thumbnails mode".

- make sure the view is set to "thumbnails"
- make sure there is enough files to scroll the view
- place the mouse cursor over one of the thumbnails (so it will be highlighted in some way) and start scrolling (SLOWLY) with mouse - when next row of thumbnails is coming under the cursor the program highlights the wrong thumbnail (one to the right instead the one under the mouse), if you keep the mouse over the last thumbnail in the row then, very often no thumbnails gets highlighted at all.

Thanks :)

**Comment by ZacWalk** [comment]
on it 👍

**Comment by ZacWalk** [comment]
@Peceha think I have a fix to this. 
I have updated the website with a new build 1022. (https://diffractor.com/download)
Thanks you for the detailed description (y)

**Comment by Peceha** [comment]
Yes, I can confirm the issue is gone :)
Thank You
