### ISSUE TITLE
'no name' folder in collection (build 1035)

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#66]
Hi,
Looks like there is additional folder showing up under "indexed" folders. There is no name assigned to it and it is not on the list in "collection option" window. See picture below
![_20210727_025531.JPG](https://user-images.githubusercontent.com/67386110/127102937-9978a4eb-a900-483c-8214-741985dae5fd.JPG)
When I start Diffractor, the program takes more than 1 minute to display the numbers of files (for the favorites and quick tags) on the side bar - I belive that delay is due to new folder being scanned (it contains info about all files on the hard drive) - in previous versions the side bar was populated with numbers  in fraction of second. 

Piotrek

**Comment by ZacWalk** [comment]
Oh - I wonder if something is weirdly configured in 'Collection Options'. Can you send a screenshot of the 'Collection Options' dialog. Maybe there is a blank line in 'other folders'?

**Comment by Peceha** [comment]
here it goes
![_20210727_031859~01.jpg](https://user-images.githubusercontent.com/67386110/127105657-cfe36130-fc8c-4b5e-930a-4e8a8e6d4ad6.jpg)
There are only 2 lines and there is no new line after g:/120... Maybe something Got corrupted in my database file...

**Comment by Peceha** [comment]
After adding "-" in front of each of these two paths I still get that "no name" folder but this time it is emty
![_20210727_033213.JPG](https://user-images.githubusercontent.com/67386110/127106708-34ccc2f5-42e7-451b-a303-58f8ed32c038.JPG)

**Comment by ZacWalk** [comment]
What happens if you delete all the folders from other folders?

**Comment by Peceha** [comment]
Hmm.. That is strange, I deleted these 2 lines, I restarted the program and nów I have 2 different folders displayed under "indexed" in side bar (i had these long time ago so looks like program is reading some old config?)
When I open collection dialog I can see only one line combined from 3 paths
![_20210727_034148.JPG](https://user-images.githubusercontent.com/67386110/127107821-2640ecc1-24ad-4393-9436-e39dca785bcc.JPG)

**Comment by Peceha** [comment]
I tried deleting that one line as well but it keeps coming back after restarting the program

**Comment by Peceha** [comment]
I forgot to add that "no name" folder is still there.

**Comment by ZacWalk** [comment]
It is importing some old settings. 
I am planning to remove that next version.
I have a theory. I just patched the app - can you try this -> https://diffractor.com/diffractor-setup.exe

**Comment by Peceha** [comment]
You fixed it ;)
Everything works like before and side bar gets populated right away.

Thanks!

**Comment by ZacWalk** [comment]
Cool! - thanks for confirming :)
