### ISSUE TITLE
Separate multiple artists in metadata

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#7]
Hi, it's me again :)
when there is more then one artist (separated by "," or "/") under ARTIST's field it is impossible to select just one of them by hoovering the mouse over the ARTIST field - always the whole field gets highlighted.
Is there a chance to have them separated? That's only my suggestion of course :)
And a picture of what I mean:
![Clipboard Image](https://user-images.githubusercontent.com/67386110/87817867-ff62ae80-c869-11ea-84bb-5a822712d451.jpg)

Thanks

**Comment by ZacWalk** [comment]
Implemented in [v123 Beta](https://diffractor.com/blog/Diffractor-v123-Beta).

**Comment by Peceha** [comment]
Working !!!! Thank You.
And I have to say it: I like the new GUI a lot - really, you did a great job there.

**Comment by ZacWalk** [comment]
Cool - thanks for confirming and the positive feedback @Peceha 
Hopefully, the new GUI will enable many improvements around managing collections of media files.
