### ISSUE TITLE
Search box doesn't always find what is needed

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#70]
Hi,
Let's say I have few files with genre:electronic. Some of these have artist:aaa. What's below works fine:
**genre:electronic -artist:aaa**
But following doesn't (I also have files with genre:dance) :
**genre:dance genre:electronic -artist:aaa**

Piotrek

**Comment by Peceha** [comment]
Looks like there is still a problem when searching directly via "searchbar" (in the latest build 1101)

If I use advance search dialog and type:
![image](https://user-images.githubusercontent.com/67386110/146048760-b883060d-d796-44b8-b963-c370d0b27e1a.png)
the result is correct (5 entries):
![image](https://user-images.githubusercontent.com/67386110/146048822-e60ae826-67b6-4a83-935c-19385a4e5bcb.png)

Please take a look at the searching phrase in "search box" - it says:
genre: electronic -artist: "depeche mode"

Now if I retype it directly into searchbox, or even "copy paste" it in place (over the original string), or the shortest way: just activate the searchbox and press ENTER (when the searching phrase is still there), then the results are wrong.
![image](https://user-images.githubusercontent.com/67386110/146049631-da054531-f587-4b75-ad54-59f792e6fddb.png)
 
Thanks.

**Comment by ZacWalk** [comment]
will take a look 👍

**Comment by ZacWalk** [comment]
Ok - I think I have a fix for this at: https://diffractor.com/diffractor-setup-test.exe

Now I need to fix all those other things :)

**Comment by Peceha** [comment]
Yes - confirmed :) searching works as expected 👍
Thank you !
