### ISSUE TITLE
Title - no action when clicking

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#77]
Hi,
I noticed that clicking on title doesn't trigger any action now (I think, some version ago, there was EDIT assigned to it).
What about finding files with the same title when clicking on it? - just the same way like other metadata fields work.

Thank you.

**Comment by ZacWalk** [comment]
I was thinking it might be useful to show the same items as the presence function. Maybe even move the presence indicator next to the title. I am wondering how often a search by name or title would be useful? What do you think?

**Comment by Peceha** [comment]
Presence function for same title actually  sounds good.
Search by a title may not be so usefull when browsing pictures but for the videos (like in my case music videos) it is quite handy (e.g. to quickly get original song + all the covered versions - that I use a lot :) )
