### ISSUE TITLE
Only one overlay icon is shown when there are more labels attached to a file

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#84]
Hi,
when you assign more than one label to a file  (ie. "Review" and "To Do" and "Approved") the program shows only one icon on top of the thumbnail (the last one that was assigned to a file) - which is a little bit confusing I think - shouldn't be all of them visible?

Thanks.

**Comment by ZacWalk** [comment]
Hey @Peceha - I am a bit late on this - sorry.

I was reading the XMP spec and it shows that only one label can be stored for a file. (I think)

![image](https://user-images.githubusercontent.com/181544/145682985-56235bb7-b631-4ff3-aeac-bd5287cfd4e8.png)

Alternatively you could use tags. What are your thoughts on this? Does you workflow need multiple labels?

**Comment by Peceha** [comment]
Hehe, I'm not in hurry :)
Looks like it was my mistake.
For some reason I was sure I saw the same file under different "labels" on the side bar - but now, after your investigation I rechecked that behavior and no - once I assign different label the item disappears from one category and jumps to the new one.

So, please remove that "not an issue" from the list :) 
...and yes, I can handle that with tags 👍
Thanks.

**Comment by ZacWalk** [comment]
Cool - all good then. By the way, I just started testing a new version at https://diffractor.com/diffractor-setup-test.exe
Let me know if you see any bugs!

**Comment by Peceha** [comment]
Thanks !
Downloading...
