### ISSUE TITLE
Add option to not update file modified timestamp when changing file metadata

### ISSUE THREAD

**Issue by JFinis** [diffractor/diffractor#86]
Diffractor changes the modified-at and also the created-at timestamp to the current time, whenever I change the metadata of a file.

As the modified-at stamp is important for me, that basically means I can't use diffractor :(. 

Would it be possible to have an option to leave the modified-at timestamp where it is when metadata is changed?

**Comment by ZacWalk** [comment]
I believe it should only currently change the modified file data. (Not the created date). This is a side affect of modifying the files metadata.

Happy to put this on my TODO list. Will not make the next release (124.0) but hopefully a subsequent release soon after.
