### ISSUE TITLE
[build 1101] wrong glyphs/fonts in description

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#87]
Hi,
please look at the picture
![image](https://user-images.githubusercontent.com/67386110/146186549-522bf3d2-5c12-4f9c-babc-45701185066d.png)
Location, Artist and Tags have wrong "picture" fonts

and here,
![image](https://user-images.githubusercontent.com/67386110/146186683-1c445060-cfdc-4390-af38-49af2784abc8.png)
Rating doesn't show stars only something else.

That's on windows 11 if that matters.
Thanks

Edit
Or maybe there is something wrong on my side... ?

**Comment by ZacWalk** [comment]
Seems a problem with dwrite rendering the icon font.
I think I have a fix for Win8 (and newer os's)  in build 1105 (https://diffractor.com/diffractor-setup-test.exe)
Windows 7 still seems broken. Spent a lot of time on that but so far no luck.
I am interested this looks ok to you in Window 11?
