### ISSUE TITLE
[build 1101+1102] thumbnail's size keeps changing when clicking on it

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#88]
Hi,
I'm sure this was introduced in 1101 - I have not seen it before.
When you click on the thumbnail its size may change (sometimes it's changing, sometimes not). Surrounding thumbnails change the size as well.
Below you can see some pictures showing the same portion of window (same thumbs) , just clicked few times:
![image](https://user-images.githubusercontent.com/67386110/146423347-d33220f3-083a-443a-9589-0bedba198a50.png)
![image](https://user-images.githubusercontent.com/67386110/146423369-59bfadfe-e162-4ccd-8708-8d8ee0aaf1aa.png)
![image](https://user-images.githubusercontent.com/67386110/146423385-9f202c06-2bb2-41c9-b571-4225dc39a839.png)
![image](https://user-images.githubusercontent.com/67386110/146423400-cd01fa1f-74ac-4f31-8f3c-694304046c6e.png)

I hope it's not going to be difficult to fix since this one can really make you confused when clicking around :)

Thanks.

**Comment by ZacWalk** [comment]
This is a tricky one. I have a possible fix in build 1105 (https://diffractor.com/diffractor-setup-test.exe)
I am interested if it is a better experience for you.

**Comment by Peceha** [comment]
Yes - all is fine now, the thumbs sizes are steady - this was quite important for me because it was difficult to track the files when the display was different every time I clicked on it.
Thank you 👍
