### ISSUE TITLE
Cannot "bulk remove" tag when there is more than one word in it

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#89]
Hi,
when doing something like below works fine:
-thisismytag

but following ia a "no go":
-"this is my tag"

I'm talking here about tag window [t].

Thanks

**Comment by ZacWalk** [comment]
I think I have a fix for this in Build 1105:  https://diffractor.com/diffractor-setup-test.exe

**Comment by Peceha** [comment]
Working now 👍 
Thanks!
