### ISSUE TITLE
[FEATURE REQUEST] enable wildcards when searching in the scopes

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#90]
Hi,
I was trying to find all the files with the "artist" starting with "A" - so I though I would do:
`artist:a*`
unfortunately it failed - looks like wildcards are only allowed with filenames.

Could it be possible to use wildcard in the example I gave above?
Thanks.

**Comment by ZacWalk** [comment]
I have added the wildcard '*' support to the current version of 124.0 - in build 1108. 
It also supports folder names with a double star. For example "*scan**" finds all files in the scan folder.
Can be downloaded from: https://diffractor.com/download

**Comment by Peceha** [comment]
Yes ! 
You made my day :) I was already adding some dummy tags like "a" "b" ... to have some kind of alphabetical searching in scopes (actually "artist" scope).

Thanks!
