### ISSUE TITLE
Tags with space at the end

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#92]
Hi,
100% accidently I added a tag with a space at the end (but, at that time, I had no idea about that space):
![image](https://user-images.githubusercontent.com/67386110/147218047-a67602d7-e5cf-4af0-8c2b-4a23fd6bf5e3.png)

And it took me few hours to get rid of this :) since Diffractor trims that last space when showing the tag:
![image](https://user-images.githubusercontent.com/67386110/147218440-ab58b8fa-e0e1-4826-82ee-e0618aae5d47.png)

So I was trying:
`-"with space"`
but of course it didn't work.
Finally I looked inside the file and noticed that there is a space at the end of the tag :)

Thanks.

**Comment by ZacWalk** [comment]
oh - that must be annoying! I will fix the tag dialog to not trim in next version/build. Probably after Christmas.

**Comment by Peceha** [comment]
As long as I know about that small behavior it is not annoying anymore -... but it was, hehehe.
There is no hurry at all, most important that all such small things will get fixed sooner or later 👍 

Thanks.
