### ISSUE TITLE
Folders thumbs are shown when using WITHOUT:

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#93]
Hi,
that one is new - it was not like this in earlier versions.

Try:
`without:artist` or `without:show` or something like that

You will get all the files missing these scopes (which is correct)  + FOLDERS (wrong)

![image](https://user-images.githubusercontent.com/67386110/147244293-51b1b8d7-8f93-4975-8a43-6bad4c8f2078.png)
![image](https://user-images.githubusercontent.com/67386110/147244371-f15040a5-2eba-45e8-bb2b-397d6541d361.png)

**Comment by ZacWalk** [comment]
Fixed in latest build 1109 -> https://diffractor.com/diffractor-setup.exe

**Comment by Peceha** [comment]
Confirmed, all back to normal 👍 
Thanks.
