### ISSUE TITLE
Caption/Description - mixed up

### ISSUE THREAD

**Issue by Peceha** [diffractor/diffractor#97]
Hi,
I was trying to find files with
"with:caption"
since the GUI shows that scope (in edit window):
![image](https://user-images.githubusercontent.com/67386110/149848597-18d5de09-06af-467e-92d4-df6bd27c1c0b.png)

but it turns out I need to use
"with:description"
which is also used in GUI but under preview window
![image](https://user-images.githubusercontent.com/67386110/149848693-7ac38e26-35f0-49be-9bb4-316ff5f1ec77.png)

"with:caption" just doesn't find anything.

Thanks.

**Comment by ZacWalk** [comment]
Ok, will investigate a fix for that.

**Comment by ZacWalk** [comment]
Build 1126 released today has fixes to:
- Use the text description instead of caption
- Support caption for with/without if the user does enter it
- Has auto-complete in the main address bar for with/without

Hope that covers it :)
